[pytest]
DJANGO_SETTINGS_MODULE = leadgen.test_settings
python_files = tests.py test_*.py *_tests.py
addopts = --cov=leadgen --cov=leads --cov-config=.coveragerc --cov-report=term-missing --cov-report=xml --cov-fail-under=80
