# Generated by Django 6.0.2 on 2026-02-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='problem_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
