# Generated by Django 6.0.2 on 2026-02-14 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_phone_lead_problem_statement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='found_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='link',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='service',
        ),
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.CharField(blank=True, default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
