# Generated by Django 6.0.2 on 2026-02-14 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_found_at_remove_lead_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='found_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lead',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
