# Generated by Django 6.0.3 on 2026-03-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_found_at_lead_link_lead_location_lead_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
