# Generated by Django 5.2.17 on 2026-09-16 10:57

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_lead_owner_i_66e55a_idx',
            old_name='leads_lead_owner_i_b69f32_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(blank=True, default='unknown', help_text='Business category or service type', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, help_text='Unique email address of the lead', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='found_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this lead was discovered'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the email has been verified'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='link',
            field=models.URLField(blank=True, help_text='URL to the original source or profile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, help_text='Geographic location of the lead', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (international format preferred)', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='Description of the problem or service request'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, help_text='Specific service offered or needed', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(help_text='Source platform (e.g., upwork, reddit, x, google-maps)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='leads_lead_source_200868_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['category'], name='leads_lead_categor_8e6059_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_verified'], name='leads_lead_is_veri_28178f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'),
        ),
    ]
